{% set name = "tensorly-torch" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tensorly-torch-{{ version }}.tar.gz
  sha256: 4c2f19f361113ca78f09b504a786075b0f51425468ae997a5f8018d4be6a4db5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - nose
    - numpy
    - scipy
    - pytorch >=1.5.1
    - tensorly

test:
  imports:
    - tltorch
    - tltorch.factorized_layers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tensorly/tensorly-torch
  summary: Deep Learning with Tensors in Python, using PyTorch and TensorLy.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    TensorLy-Torch is a Python library for deep tensor networks that builds 
    on top of [TensorLy][_tensorly] and [PyTorch][_pytorch]. It allows to 
    easily leverage tensor methods in a deep learning setting and comes with 
    all batteries included.

    [_tensorly]: https://github.com/tensorly/tensorly/
    [_pytorch]: https://pytorch.org/

  doc_url: http://tensorly.org/torch/dev/
  dev_url: https://github.com/tensorly/tensorly-torch

extra:
  recipe-maintainers:
    - sugatoray
